// import "./components/hero_slider.js";
import "./components/preloader.js";
import "./components/modals.js";
// import "./components/marquee_slider.js";
import "./components/mask.js";
import "./components/accordeon.js";
import "./components/menu.js";
import "./components/selects.js";
import "./components/fancybox.js";
import "./components/slider.js";
import "./components/tabs.js";
import "./components/scrollbar.js";
// import "./components/burger.js";
import "./components/validation.js";
import "./components/filters.js";
import "./components/location.js";
import "./components/fixed_header.js";
import "./components/quiz.js";
import "./components/calendar.js";
import "./components/to-up.js";
import "./components/animation.js";
